listen: 1031
pollingInterval: 1000
startWithRetrieverError: false
retriever:
  kind: mongodb
  collection: featureFlags
  database: appConfig
  uri: mongodb://root:example@127.0.0.1:27017/

exporter:
  kind: log
enableSwagger: true
